name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Add ~/.local/bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Python packages
        run: |
          pip install cython
          pip install buildozer

      - name: Accept Licenses Forcefully
yes | yes |         run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Inject SDK Licenses
        run: |
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/licenses
          cp .github/licenses/* $HOME/.buildozer/android/platform/android-sdk/licenses/
          cp .github/licenses/platform-tools-license "$HOME/.buildozer/android/platform/android-sdk/licenses/platform-tools-license"

      - name: Preinstall SDK components
        run: |
yes | yes |           yes | sdkmanager \
            "platform-tools" \
            "build-tools;34.0.0" \
            "platforms;android-34" 2>> errors.log

      - name: Inject Licenses Again
        run: ./.github/scripts/inject_licenses.sh 2>> errors.log

      - name: Build APK
        env:
          ANDROID_SDK_ROOT: "$HOME/.buildozer/android/platform/android-sdk"
          PATH: "$HOME/.buildozer/android/platform/android-sdk/build-tools/34.0.0:$PATH"
        run: buildozer android debug 2>> errors.log

      - name: Upload Error Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: errors.log