name: Build and Release APK
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - name: Download ONNX Models
      run: bash app/scripts/download_models.sh
    - name: Setup Gradle Wrapper
      run: |
        gradle wrapper
        chmod +x ./gradlew
    - name: Build APK
      run: ./gradlew assembleDebug
    - name: Create GitHub Release\n      uses: softprops/action-gh-release@v2\n      with:\n        upload_url: ${{ github.event.release.upload_url }}\n        asset_path: app/build/outputs/apk/debug/app-debug.apk\n        asset_name: app-debug.apk\n        asset_content_type: application/vnd.android.package-archive
