name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "17"

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept licenses
      run: yes | sdkmanager --licenses

    - name: Install SDK packages
      run: sdkmanager "build-tools;34.0.0" "platforms;android-34" "platform-tools"

    - name: Restore gradle-wrapper.jar
      run: curl -sL https://services.gradle.org/distributions/gradle-8.1.1-bin.zip | bsdtar -xvf- -C gradle --strip-components=2 gradle-8.1.1/lib/gradle-wrapper.jar

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: app/build/outputs/apk/debug/app-debug.apk
