name: Android Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify gradlew exists
        shell: bash
        run: |
          if ! command -v gradle >/dev/null; then
            echo "gradlew missing or not executable"
            exit 1
          fi

      - name: Assemble debug APK
        shell: bash
        run: gradle assembleDebug

      - name: Verify APK
        id: verify_apk
        shell: bash
        run: |
          APK=app/build/outputs/apk/debug/app-debug.apk
          if [[ -f "$APK" ]]; then
            echo "apk_found=true" >> "$GITHUB_OUTPUT"
          else
            echo "APK not found" >&2
            exit 1
          fi

      - name: Create Release
        if: steps.verify_apk.outputs.apk_found == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/debug/app-debug.apk
