---
name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses || true
        with:
          packages: |
            platform-tools
            build-tools;34.0.0
            platforms;android-34

      - name: Install Python packages
        run: |
          pip install cython
          pip install buildozer

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: bin/*.apk
