name: Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Set JAVA_HOME to Java 17
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "/usr/lib/jvm/java-17-openjdk-amd64/bin" >> $GITHUB_PATH
          packages: |
            platform-tools
            build-tools;34.0.0
            platforms;android-34

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip unzip zip openjdk-17-jdk wget


      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: bin/*.apk
